---


- set_fact: java_state="present"

- set_fact: java_state="latest"
  when: update_java == true

- name: RedHat - Ensure Java is installed
  yum: name={{ java }} state={{java_state}}
  when: ansible_os_family == 'RedHat'
  
- name: Add Oracle java repository
  apt_repository: repo='ppa:webupd8team/java'
  when: (ansible_os_family == 'Debian' and
        use_oracle_java is defined and
        use_oracle_java)

- name: Accept Java 8 License
  debconf: name='{{ oracle_java }}' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  when: (ansible_os_family == 'Debian' and
        use_oracle_java is defined and
        use_oracle_java)

- name: Debian - Ensure Java is installed
  apt: name={{ java }} state={{java_state}} update_cache=yes force=yes
  when: (ansible_os_family == 'Debian' and
        use_oracle_java is not defined)

- name: Debian - Ensure Java is installed
  apt: name={{ item }} state={{java_state}} update_cache=yes force=yes
  with_nested:
              - "{{ oracle_java }}"
              - "{{ oracle_java_defaults }}"
  when: (ansible_os_family == 'Debian' and
        use_oracle_java is defined and
        use_oracle_java)
